"""added user_id to address table and added User table

Revision ID: 1d270b90cb41
Revises: 8a6fb1b9c22b
Create Date: 2022-08-19 17:17:21.620507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d270b90cb41'
down_revision = '8a6fb1b9c22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('address', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'address', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
